debian/tmp/etc/
debian/tmp/usr/bin/
debian/tmp/usr/share/applications/
debian/tmp/usr/include/
debian/tmp/usr/share/doc
debian/tmp/usr/share/man
contrib/dump-asy.pl usr/share/doc/i3-wm/examples/
contrib/gtk-tree-watch.pl usr/share/doc/i3-wm/examples/
contrib/i3-wsbar usr/share/doc/i3-wm/examples/
contrib/per-workspace-layout.pl usr/share/doc/i3-wm/examples/
contrib/trivial-bar-script.sh usr/share/doc/i3-wm/examples/
